### PR TITLE
Add converted files

### PR DESCRIPTION
**Pull request by mrshirts**
Raw dump of converted files. Comparisons are in convert_output_SAMPL6_cutoff.txt and convert_output_SAMPL6_ewald.txt with two different types of nonbonded cutoffs.

Please add here additional information you would like to see in a README, and if you want me to delete some of the files (like stdout and stderr of programs runs), or any suggestions for reorganization.

### CODE REVIEW

**Comment by davidlmobley** [comment]
@mrshirts - OK, going through this, so it looks like I'd want:
- Main README.md updated to note availability of these files and acknowledgement of yourself, links to ParmEd and InterMol. (Update changelog too!)
- Host-guest README.md updated to briefly note conversion process/link to where it is described in detail (probably a `conversion.md` file in the SAMPLing directory?)
- `conversion.md` or similar in SAMPLing directory which briefly explains organization of subdirectories (right now there'snothing which says what the files are, that I can find -- for example, I don't recognize a "*_simbox.dat" file. This would probably also be a good place to briefly summarize the results of your conversion, e.g. all of the results agree well across packages with cutoffs  (??) but with Ewald there are discrepancies of (???) as you might expect (??). Make sure to link to/mention this from the other READMEs above.
- I think it would be good to delete the standard out and standard error of the different program runs; right now it takes a good long time to even check out the repo on my computer, let alone to download it... 

One of the above will presumably need to describe exactly how you did/validated the conversion since I don't see that here at present...?

Also I'd note the following:
- Your job may now be much smaller/easier if indeed we only provide/convert files for the three compounds involved in the SAMPLing component (see #11 )

I'm happy to do the updates to the main README files noting that these are available if you can do the `conversion.md` or similar which describes the actual conversion.

But this seems to be on the right track; thanks for your work on it. The organization seems basically fine to me. One minor improvement might perhaps to be to make it so the systems in `SAMPLing` are named `converted_...." rather than `..._converted` so that all of the conversion-related stuff alphabetizes together in an `ls`. Otherwise it is a bit of a mess trying to see what's even present there. 

@andrrizzi, any other thoughts?

**Comment by davidlmobley** [comment]
@mrshirts - Andrea and I talked, and he's going to bring in his updated files in two phases; you can wait on doing the (very sorry!) re-conversion until both are done:
1) SAMPLing files -- specifically, three ligands only
2) Full files for reference calculations (which will include all ligands, and the SAMPLing files will be a subset)

Should we close this issue and do a separate PR at that point?

**Comment by mrshirts** [comment]
Sure, that's fine.  I'll pull down everything fresh, and reprocess.  

It's not much work to the conversion for extra ligands - it's just the bookkeeping after it's converted.

**Comment by davidlmobley** [comment]
Closing this for now, then.

**Comment by mrshirts** [comment]
Just wanted to confirm -- the files are the final versions now, correct?  I don't recall hearing, and nobody has been bugging me about them, so I wanted to check.

**Comment by davidlmobley** [comment]
We are still waiting for @andrrizzi to provide the rest of the inputs for the reference calculations he has running. In other words, we have final files for three host-guest complexes out of the full set of 30ish cases at this point.

**Comment by mrshirts** [comment]
So, I should wait, or go ahead and convert the set? Apologies if I'm missing something.

**Comment by davidlmobley** [comment]
I would wait til you can do them all at once, unless someone starts asking for the files. We want the full set converted eventually, so if you do the files that are here now then I'll just have to ask you to convert again later. 

The plan is still that I contact you once Andrea deposits the rest of the files so you can do them all in one batch.

**Comment by andrrizzi** [comment]
Correct. To be more specific, these are the final files for the SAMPLing challenge only.

I'll share also the input files that I'll use to run reference calculations for the standard host-guest SAMPL challenge, but these files will be independent of the ones I've uploaded (I'll need to regenerate files for these three molecules too).

These files will probably be ready at the end of next week or soon after that so it is probably more convenient for you to wait for all the files and convert everything in a single pass.

**Comment by mrshirts** [comment]
Can do.

**Pull request closed without merging**
