### PR TITLE
Add empirical reference calculations to logP analyis.

### PR DESCRIPTION
**Pull request by MehtapIsik**
These PR adds a variety of empirical logP prediction methods (submitted by Thomas Fox) to logP challenge analysis.

- REF09: clogP (Biobyte)
- REF10: h_logP (MOE)
- REF11: logP(o/w) (MOE)
- REF12: MoKa_logP
- REF13: SlogP (MOE)

### CODE REVIEW

**Comment by bergazin** [comment]
Looks good to me.

**Comment by davidlmobley** [comment]
@MehtapIsik mostly looks good, except I think you've also updated lots of plots that haven't changed, at the same time? Specifically (for example) the absolute error plots for all of the individual submissions.

I'm guessing you just re-ran the analysis script, but then committed all of the files whether they had changed or not?

**Comment by MehtapIsik** [comment]
Yes, correct. My script replotted all those. Even if nothing changes, something changes in PDF binary files. So I committed all those new plots.

**Comment by davidlmobley** [comment]
Right, so the way I would have done it would have been to only commit files which changed so that the revision history doesn't look like we updated everything.

If it's too much trouble to roll that back we can go ahead with what you've committed, but I worry it will make the revision history confusing to have all these plots "updated" after the challenge.

**Comment by MehtapIsik** [comment]
I know it is crowding the revision history but it is too hard to differentiate between PDFs that were really updated and PDFs that look like they were updated. I am afraid to cause a mixture of new and old files and introduce mistakes if I try to avoid these. It is better to merge as is.

**Pull request merged**
