### PR TITLE
update logP analysis with 2 reference calculations

### PR DESCRIPTION
**Pull request by MehtapIsik**
This PR adds 2 reference calculations to logP challenge analysis:
- `zxcvb` - GAFF + tip3p
- `zaqws` - GAFF + tip3pFB

It also corrects a file naming mistake of one of the blind submissions (`vzgyt-1559-logP-shin-1.csv`) which was interrupting the analysis script.

### CODE REVIEW

**Comment by MehtapIsik** [comment]
I like the idea of using separate submission IDs for references. We can use capital letters even to distinguish better: `REF01`, `REF02`, ....  I had used previously `nbXXX` scheme for non-blind pKa change predictions. Which one is preferable?

We can make plots of reference and blind submissions separately too, but I think we should keep the plots that show everything together as well.

**Comment by MehtapIsik** [comment]
I prefer that we update reference submissions in a new PR instead of reverting this. Is that acceptable?

**Comment by davidlmobley** [comment]
Yes, a new PR is fine. And I'm enthusiastic about uppercase letters, `REF01` etc sound good.

**Comment by MehtapIsik** [comment]
OK. @bergazin and I will update submission IDs accordingly.

**Pull request merged**
